## Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.debug=false

## Mappings Properties
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Environment Properties
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.173
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
# https://choosealicense.com/
# https://semver.org/
# https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_id=pillaged
mod_name=Pillage'd
mod_license=All Rights Reserved
mod_version=0.0.1
mod_group_id=net.grizdor.pillaged
mod_authors=TheGameAce, Grizdor
mod_description=Pillage'd is an Illagers Overhaul mod for Minecraft.
